# Generated by Django 5.2.4 on 2025-07-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30),
            preserve_default=False,
        ),
    ]
