# Generated by Django 5.2.4 on 2025-07-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='correct_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='total_questions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
