# Generated by Django 5.2.4 on 2025-07-11 08:26

# from django.db import migrations


# class Migration(migrations.Migration):

#     dependencies = [
#         ('teachers', '0001_initial'),
#     ]

#     operations = [
#     ]

from django.db import migrations

def truncate_teacher_records(apps, schema_editor):
    Teacher = apps.get_model('teachers', 'Teacher')
    Teacher.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),  # Replace with actual last migration name
    ]

    operations = [
        migrations.RunPython(truncate_teacher_records),
    ]
