# Generated by Django 5.2.4 on 2025-08-07 12:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrequest',
            name='approval_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]


