# Generated by Django 5.2.4 on 2025-08-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chatrequest_approval_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrequest',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
