# Generated by Django 5.2.4 on 2025-08-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_chatrequest_cancelled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrequest',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
