# Generated by Django 5.2.4 on 2025-08-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not Submitted'), (1, 'Submitted'), (2, 'Overdue')], default=0),
        ),
    ]
